# 01. 순환 신경망(Recurrent Neural Network, RNN)
RNN(Recurrent Neural Network)은 시퀀스(Sequence) 모델입니다. 입력과 출력을 시퀀스 단위로 처리하는 모델입니다. 번역기를 생각해보면 입력은 번역하고자 하는 문장. 즉, 단어 시퀀스입니다. 출력에 해당되는 번역된 문장 또한 단어 시퀀스입니다. 이러한 시퀀스들을 처리하기 위해 고안된 모델들을 시퀀스 모델이라고 합니다. 그 중에서도 RNN은 딥 러닝에 있어 가장 기본적인 시퀀스 모델입니다.

> 용어는 비슷하지만 순환 신경망과 재귀 신경망(Recursive Neural Network)은 전혀 다른 개념입니다.  


## 1. 순환 신경망(Recurrent Neural Network, RNN)
앞서 배운 신경망들은 전부 은닉층에서 활성화 함수를 지난 값은 오직 출력층 방향으로만 향했습니다. 이와 같은 신경망들을 `피드 포워드 신경망(Feed Forward Neural Network)`이라고 합니다. 그런데 그렇지 않은 신경망들이 있습니다. `RNN(Recurrent Neural Network)` 또한 그 중 하나입니다. RNN은 은닉층의 노드에서 활성화 함수를 통해 나온 결과값을 출력층 방향으로도 보내면서, 다시 은닉층 노드의 다음 계산의 입력으로 보내는 특징을 갖고있습니다.

![](https://wikidocs.net/images/page/22886/rnn_image1_ver2.PNG)



이를 그림으로 표현하면 위와 같습니다. x는 입력층의 입력 벡터, y는 출력층의 출력 벡터입니다. 실제로는 편향 b도 입력으로 존재할 수 있지만 앞으로의 그림에서는 생략합니다. RNN에서 은닉층에서 활성화 함수를 통해 결과를 내보내는 역할을 하는 노드를 `셀(cell)`이라고 합니다. __이 셀은 이전의 값을 기억하려고 하는 일종의 메모리 역할을 수행하므로 이를 `메모리 셀` 또는 `RNN 셀`이라고 표현합니다.__

__은닉층의 메모리 셀은 각각의 `시점(time step)`에서 바로 이전 시점에서의 은닉층의 메모리 셀에서 나온 값을 자신의 입력으로 사용하는 재귀적 활동을 하고 있습니다.__ 앞으로는 현재 시점을 변수 t로 표현하겠습니다. 이는 현재 시점 t에서의 메모리 셀이 갖고있는 값은 과거의 메모리 셀들의 값에 영향을 받은 것임을 의미합니다. 그렇다면 메모리 셀이 갖고 있는 이 값은 뭐라고 부를까요?

__메모리 셀이 출력층 방향으로 또는 다음 시점 t+1의 자신에게 보내는 값을 `은닉 상태(hidden state)`라고 합니다.__ 다시 말해 t 시점의 메모리 셀은 t-1 시점의 메모리 셀이 보낸 은닉 상태값을 t 시점의 은닉 상태 계산을 위한 입력값으로 사용합니다.

![](https://wikidocs.net/images/page/22886/rnn_image2_ver3.PNG)


RNN을 표현할 때는 일반적으로 위의 그림에서 좌측과 같이 화살표로 사이클을 그려서 재귀 형태로 표현하기도 하지만, 우측과 같이 사이클을 그리는 화살표 대신 여러 시점으로 펼쳐서 표현하기도 합니다. 두 그림은 동일한 그림으로 단지 사이클을 그리는 화살표를 사용하여 표현하였느냐, 시점의 흐름에 따라서 표현하였느냐의 차이일 뿐 둘 다 동일한 RNN을 표현하고 있습니다.

피드 포워드 신경망에서는 뉴런이라는 단위를 사용했지만, __RNN에서는 뉴런이라는 단위보다는 입력층과 출력층에서는 각각 입력 벡터와 출력 벡터, 은닉층에서는 은닉 상태라는 표현을 주로 사용합니다.__ 그래서 사실 위의 그림에서 회색과 초록색으로 표현한 각 네모들은 기본적으로 벡터 단위를 가정하고 있습니다. 피드 포워드 신경망과의 차이를 비교하기 위해서 RNN을 뉴런 단위로 시각화해보겠습니다.

![](https://wikidocs.net/images/page/22886/rnn_image2.5.PNG)

위의 그림은 입력 벡터의 차원이 4, 은닉 상태의 크기가 2, 출력층의 출력 벡터의 차원이 2인 RNN이 시점이 2일 때의 모습을 보여줍니다. 다시 말해 뉴런 단위로 해석하면 입력층의 뉴런 수는 4, 은닉층의 뉴런 수는 2, 출력층의 뉴런 수는 2입니다.

![](https://wikidocs.net/images/page/22886/rnn_image3_ver2.PNG)

__RNN은 입력과 출력의 길이를 다르게 설계 할 수 있으므로 다양한 용도로 사용할 수 있습니다.__ 위 그림은 입력과 출력의 길이에 따라서 달라지는 RNN의 다양한 형태를 보여줍니다. 위 구조가 자연어 처리에서 어떻게 사용될 수 있는지 예를 들어봅시다. RNN 셀의 각 시점 별 입, 출력의 단위는 사용자가 정의하기 나름이지만 가장 보편적인 단위는 '단어 벡터'입니다.

예를 들어 __하나의 입력에 대해서 여러개의 출력(one-to-many)의 모델은 하나의 이미지 입력에 대해서 사진의 제목을 출력하는 이미지 캡셔닝(Image Captioning) 작업에 사용할 수 있습니다.__ 사진의 제목은 단어들의 나열이므로 시퀀스 출력입니다.


![](https://wikidocs.net/images/page/22886/rnn_image3.5.PNG)

__또한 단어 시퀀스에 대해서 하나의 출력(many-to-one)을 하는 모델은 입력 문서가 긍정적인지 부정적인지를 판별하는 감성 분류(sentiment classification), 또는 메일이 정상 메일인지 스팸 메일인지 판별하는 스팸 메일 분류(spam detection)에 사용할 수 있습니다.__ 위 그림은 RNN으로 스팸 메일을 분류할 때의 아키텍처를 보여줍니다.

![](https://wikidocs.net/images/page/22886/rnn_image3.7.PNG)

__다 대 다(many-to-many)의 모델의 경우에는 입력 문장으로 부터 대답 문장을 출력하는 챗봇과 입력 문장으로부터 번역된 문장을 출력하는 번역기, 개체명 인식이나 품사 태깅과 같은 작업이 속합니다.__ 위 그림은 개체명 인식을 수행할 때의 RNN 아키텍처를 보여줍니다.

이제 RNN에 대한 수식을 정의해보겠습니다.

![](https://wikidocs.net/images/page/22886/rnn_image4_ver2.PNG)

현재 시점 t에서의 은닉 상태값을 ht라고 정의하겠습니다. 은닉층의 메모리 셀은 ht를 계산하기 위해서 __총 두 개의 가중치__ 를 갖게 됩니다. 하나는 입력층에서 입력값을 위한 가중치 Wx이고, 하나는 이전 시점 t-1의 은닉 상태값인 ht−1을 위한 가중치 Wh입니다.

이를 식으로 표현하면 다음과 같습니다.


- 은닉층 : $h_t=tanh(W_xx_t+W_hh_{t−1}+b)$

- 출력층 : $y_t=f(W_yh_t+b)$

    - 단, f는 비선형 활성화 함수 중 하나.

RNN의 은닉층 연산을 벡터와 행렬 연산으로 이해할 수 있습니다. 자연어 처리에서 RNN의 입력 xt는 대부분의 경우에서 단어 벡터로 간주할 수 있는데, 단어 벡터의 차원을 d라고 하고, 은닉 상태의 크기를 Dh라고 하였을 때 각 벡터와 행렬의 크기는 다음과 같습니다.

- $x_t : (d×1)$
- $W_x : (D_h×d)$
- $W_h : (D_h×D_h)$
- $h_{t−1} : (D_h×1)$
- $b : (D_h×1)$

배치 크기가 1이고, d와 Dh 두 값 모두를 4로 가정하였을 때, RNN의 은닉층 연산을 그림으로 표현하면 아래와 같습니다.

![](https://wikidocs.net/images/page/22886/rnn_images4-5.PNG)

__이때 ht를 계산하기 위한 활성화 함수로는 주로 하이퍼볼릭탄젠트 함수(tanh)가 사용되지만, ReLU로 바꿔 사용하는 시도도 있습니다.__

__위의 식에서 각각의 가중치 Wx, Wh, Wy의 값은 모든 시점에서 값을 동일하게 공유합니다. 만약, 은닉층이 2개 이상일 경우에는 은닉층 2개의 가중치는 서로 다릅니다.__

__출력층은 결과값인 yt를 계산하기 위한 활성화 함수로는 상황에 따라 다를텐데, 예를 들어서 이진 분류를 해야하는 경우라면 시그모이드 함수를 사용할 수 있고 다양한 카테고리 중에서 선택해야하는 문제라면 소프트맥스 함수를 사용하게 될 것입니다.__



***

##  2. 파이썬으로 RNN 구현하기
직접 Numpy로 RNN 층을 구현해보겠습니다. 앞서 메모리 셀에서 은닉 상태를 계산하는 식을 다음과 같이 정의하였습니다.

$h_t=tanh(W_xx_t+W_hh_{t−1}+b)$

실제 구현에 앞서 간단히 의사 코드(pseudocode)를 작성해보겠습니다.

```
# 아래의 코드는 의사 코드(pseudocode)로 실제 동작하는 코드가 아님. 

hidden_state_t = 0 # 초기 은닉 상태를 0(벡터)로 초기화
for input_t in input_length: # 각 시점마다 입력을 받는다.
    output_t = tanh(input_t, hidden_state_t) # 각 시점에 대해서 입력과 은닉 상태를 가지고 연산
    hidden_state_t = output_t # 계산 결과는 현재 시점의 은닉 상태가 된다.
```

우선 t 시점의 은닉 상태를 hidden_state_t라는 변수로 선언하였고, 입력 데이터의 길이를 input_length로 선언하였습니다. 이 경우, 입력 데이터의 길이는 곧 총 시점의 수(timesteps)가 됩니다. 그리고 t 시점의 입력값을 input_t로 선언하였습니다. 각 메모리 셀은 각 시점마다 input_t와 hidden_sate_t(이전 상태의 은닉 상태)를 입력으로 활성화 함수인 하이퍼볼릭탄젠트 함수를 통해 현 시점의 hidden_state_t를 계산합니다.

의사 코드를 통해 간단히 개념 정립을 해보았습니다. 이제 RNN 층을 실제 동작되는 코드로 구현해보겠습니다. 아래의 코드는 이해를 돕기 위해 (timesteps, input_size) 크기의 2D 텐서를 입력으로 받았다고 가정하였으나, 실제로 파이토치에서는 (batch_size, timesteps, input_size)의 크기의 3D 텐서를 입력으로 받는 것을 기억합시다.

In [1]:
import numpy as np

timesteps = 10 # 시점의 수. NLP에서는 보통 문장의 길이가 된다.
input_size = 4 # 입력의 차원. NLP에서는 보통 단어 벡터의 차원이 된다.
hidden_size = 8 # 은닉 상태의 크기. 메모리 셀의 용량이다.

inputs = np.random.random((timesteps, input_size)) # 입력에 해당되는 2D 텐서

hidden_state_t = np.zeros((hidden_size,)) # 초기 은닉 상태는 0(벡터)로 초기화
# 은닉 상태의 크기 hidden_size로 은닉 상태를 만듬.

우선 시점, 입력의 차원, 은닉 상태의 크기, 그리고 초기 은닉 상태를 정의하였습니다. 현재 초기 은닉 상태는 0의 값을 가지는 벡터로 초기화가 된 상태입니다. 초기 은닉 상태를 출력해보겠습니다.



In [3]:
print(hidden_state_t) # 8의 크기를 가지는 은닉 상태. 현재는 초기 은닉 상태로 모든 차원이 0의 값을 가짐.


[0. 0. 0. 0. 0. 0. 0. 0.]


은닉 상태의 크기를 8로 정의하였으므로 8의 차원을 가지는 0의 값으로 구성된 벡터가 출력됩니다. 이제 가중치와 편향을 정의합니다.



In [4]:
Wx = np.random.random((hidden_size, input_size))  # (8, 4)크기의 2D 텐서 생성. 입력에 대한 가중치.
Wh = np.random.random((hidden_size, hidden_size)) # (8, 8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치.
b = np.random.random((hidden_size,)) # (8,)크기의 1D 텐서 생성. 이 값은 편향(bias).


가중치와 편향을 각 크기에 맞게 정의하였습니다. 가중치와 편향의 크기를 출력해보겠습니다.



In [5]:
print(np.shape(Wx))
print(np.shape(Wh))
print(np.shape(b))

(8, 4)
(8, 8)
(8,)


각 가중치와 편향의 크기는 다음과 같습니다. Wx는 (은닉 상태의 크기 × 입력의 차원), Wh는 (은닉 상태의 크기 × 은닉 상태의 크기), b는 (은닉 상태의 크기)의 크기를 가집니다. 이제 모든 시점의 은닉 상태를 출력한다고 가정하고, RNN 층을 동작시켜봅시다.



In [9]:
total_hidden_states = []

# 메모리 셀 동작
for input_t in inputs: # 각 시점에 따라서 입력값이 입력됨.
    output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t) + b) # Wx * Xt + Wh * Ht-1 + b(bias)
    total_hidden_states.append(list(output_t)) # 각 시점의 은닉 상태의 값을 계속해서 축적
    print(np.shape(total_hidden_states)) # 각 시점 t별 메모리 셀의 출력의 크기는 (timestep, output_dim)
    hidden_state_t = output_t

total_hidden_states = np.stack(total_hidden_states, axis = 0) 
# 출력 시 값을 깔끔하게 해준다.

print(total_hidden_states) # (timesteps, output_dim)의 크기. 이 경우 (10, 8)의 크기를 가지는 메모리 셀의 2D 텐서를 출력.

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.99999566 0.99997765 0.99999722 0.99999219 0.99999581 0.99998804
  0.99996086 0.99989574]
 [0.99999119 0.99996494 0.99999556 0.99995731 0.9999897  0.99995464
  0.99995007 0.99978897]
 [0.9999801  0.99990455 0.99998938 0.9999269  0.99996636 0.99992643
  0.99990993 0.99966111]
 [0.99999254 0.99995803 0.99999582 0.99994625 0.99998452 0.99994904
  0.99996214 0.99980256]
 [0.99997109 0.99987821 0.99998765 0.99995771 0.9999733  0.99992885
  0.99981662 0.99975103]
 [0.99998942 0.99993973 0.99999494 0.99994279 0.99998079 0.99993087
  0.99994091 0.99982137]
 [0.99999029 0.99995177 0.99999391 0.99998828 0.99999047 0.99998203
  0.9999246  0.99983472]
 [0.99999151 0.99995784 0.99999604 0.99994633 0.99998689 0.99993792
  0.99995131 0.99982983]
 [0.99997251 0.99988128 0.99998573 0.9999533  0.999968   0.99994055
  0.99985455 0.99966134]
 [0.99998164 0.99993147 0.99999302 0.99997922 0.9999894  0.99995316
  0.99983772 0.99985398]

***
## 3. 파이토치의 nn.RNN()
파이토치에서는 nn.RNN()을 통해서 RNN 셀을 구현합니다. 실습을 통해 이해해봅시다. 우선 필요한 파이토치의 도구들을 임포트합니다.



In [10]:
import torch
import torch.nn as nn

__이제 입력의 크기와 은닉 상태의 크기를 정의합니다. 은닉 상태의 크기는 대표적인 RNN의 하이퍼파라미터입니다. 여기서 입력의 크기는 매 시점마다 들어가는 입력의 크기를 의미합니다.__



In [11]:
input_size = 5 # 입력의 크기
hidden_size = 8 # 은닉 상태의 크기


이제 입력 텐서를 정의합니다. 입력 텐서는 (배치 크기 × 시점의 수 × 매 시점마다 들어가는 입력)의 크기를 가집니다. 여기서는 배치 크기는 1, 10번의 시점동안 5차원의 입력 벡터가 들어가도록 텐서를 정의합니다.



In [14]:
# (batch_size, time_steps, input_size)
inputs = torch.Tensor(1, 10, 5)

이제 nn.RNN()을 사용하여 RNN의 셀을 만듭니다. 인자로 입력의 크기, 은닉 상태의 크기를 정의해주고, batch_first=True를 통해서 입력 텐서의 첫번째 차원이 배치 크기임을 알려줍니다.



In [16]:
cell = nn.RNN(input_size, hidden_size, batch_first=True)

입력 텐서를 RNN 셀에 입력하여 출력을 확인해봅시다.

In [17]:
outputs, _status = cell(inputs)

RNN 셀은 두 개의 입력을 리턴하는데, 첫번째 리턴값은 모든 시점(timesteps)의 은닉 상태들이며, 두번째 리턴값은 마지막 시점(timestep)의 은닉 상태입니다. 우선 첫번째 리턴값에 대해서 크기를 확인해봅시다.



In [18]:
print(outputs.shape) # 모든 time-step의 hidden_state


torch.Size([1, 10, 8])


첫번째 리턴값의 은닉 상태들은 (1, 10, 8)의 크기를 가집니다. 이는 10번의 시점동안 8차원의 은닉상태가 출력되었다는 의미입니다. 두번째 리턴값. 다시 말해 마지막 시점의 은닉 상태의 크기를 확인해보겠습니다.



In [19]:
print(_status.shape) # 최종 time-step의 hidden_state


torch.Size([1, 1, 8])


마지막 시점의 은닉 상태는 (1, 1, 8)의 크기를 가집니다.



In [20]:
outputs

tensor([[[-0.3384, -0.5713,  0.0508, -0.2231,  0.2339,  0.4908,  0.3820,
           0.3998],
         [-0.2954, -0.3634,  0.0685,  0.1883,  0.4397,  0.3879,  0.4198,
           0.3534],
         [-0.3105, -0.3514,  0.0718,  0.0606,  0.2975,  0.3724,  0.4126,
           0.2828],
         [-0.3308, -0.3990,  0.0565,  0.0305,  0.3450,  0.3877,  0.4124,
           0.3338],
         [-1.0000,  1.0000, -1.0000, -1.0000,  1.0000,  1.0000,  1.0000,
          -1.0000],
         [-0.9194, -0.7001, -0.5215,  0.2692,  0.1034,  0.9194,  0.3961,
           0.2095],
         [-0.3327, -0.2313,  0.1780,  0.2364,  0.3478,  0.4266,  0.5381,
           0.6181],
         [-0.2415, -0.3317,  0.0638, -0.0237,  0.3750,  0.2591,  0.3012,
           0.2095],
         [-0.3762, -0.4319,  0.0314,  0.0473,  0.2976,  0.4521,  0.4174,
           0.3153],
         [ 1.0000,  1.0000,  1.0000,  1.0000, -1.0000,  1.0000,  1.0000,
          -1.0000]]], grad_fn=<TransposeBackward1>)

In [21]:
_status

tensor([[[ 1.,  1.,  1.,  1., -1.,  1.,  1., -1.]]], grad_fn=<StackBackward>)

In [28]:
print(list(cell.parameters())[0].shape) # W_x
print(list(cell.parameters())[1].shape) # W_h
print(list(cell.parameters())[2].shape) # W_y?
print(list(cell.parameters())[3].shape) # bias?

torch.Size([8, 5])
torch.Size([8, 8])
torch.Size([8])
torch.Size([8])


***
## 4. 깊은 순환 신경망(Deep Recurrent Neural Network)


![](https://wikidocs.net/images/page/22886/rnn_image4.5_finalPNG.PNG)


앞서 RNN도 다수의 은닉층을 가질 수 있다고 언급한 바 있습니다. 위의 그림은 순환 신경망에서 은닉층이 1개 더 추가되어 은닉층이 2개인 깊은(deep) 순환 신경망의 모습을 보여줍니다. 위의 코드에서 첫번째 은닉층은 다음 은닉층에 모든 시점에 대해서 은닉 상태 값을 다음 은닉층으로 보내주고 있습니다.

깊은 순환 신경망을 파이토치로 구현할 때는 nn.RNN()의 인자인 num_layers에 값을 전달하여 층을 쌓습니다. 층이 2개인 깊은 순환 신경망의 경우, 앞서 실습했던 임의의 입력에 대해서 출력이 어떻게 달라지는지 확인해봅시다.


In [48]:
# (batch_size, time_steps, input_size)
inputs = torch.Tensor(1, 10, 5)

In [49]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers = 2, batch_first=True)

In [50]:
outputs, _status = cell(inputs)

In [51]:
print(outputs.shape)

torch.Size([1, 10, 8])


첫번째 리턴값의 크기는 층이 1개였던 RNN 셀 때와 달라지지 않았습니다. 여기서는 마지막 층의 모든 시점의 은닉 상태들입니다.



In [52]:
print(_status.shape) # (층의 개수, 배치 크기, 은닉 상태의 크기)


torch.Size([2, 1, 8])


두번째 리턴값의 크기는 층이 1개였던 RNN 셀 때와 달라졌는데, 여기서 크기는 (층의 개수, 배치 크기, 은닉 상태의 크기)에 해당됩니다.



In [53]:
_status

tensor([[[ 0.4832,  0.5245,  0.3645,  0.1797, -0.3683,  0.0412, -0.2005,
           0.0033]],

        [[-0.0373, -0.1211,  0.2262, -0.1336, -0.0853,  0.2994,  0.5340,
           0.4149]]], grad_fn=<StackBackward>)

***

## 5. 양방향 순환 신경망(Bidirectional Recurrent Neural Network)

양방향 순환 신경망은 시점 t에서의 출력값을 예측할 때 이전 시점의 데이터뿐만 아니라, 이후 데이터로도 예측할 수 있다는 아이디어에 기반합니다.

영어 빈칸 채우기 문제에 비유하여 보겠습니다.

```
Exercise is very effective at [          ] belly fat.

1) reducing
2) increasing
3) multiplying
```

'운동은 복부 지방을 [ ] 효과적이다'라는 영어 문장이고, 정답은 reducing(줄이는 것)입니다. 그런데 위의 영어 빈 칸 채우기 문제를 잘 생각해보면 정답을 찾기 위해서는 이전에 나온 단어들만으로는 부족합니다. 목적어인 belly fat(복부 지방)를 모르는 상태라면 정답을 결정하기가 어렵습니다.

__즉, RNN이 과거 시점(time step)의 데이터들을 참고해서, 찾고자하는 정답을 예측하지만 실제 문제에서는 과거 시점의 데이터만 고려하는 것이 아니라 향후 시점의 데이터에 힌트가 있는 경우도 많습니다. 그래서 이전 시점의 데이터뿐만 아니라, 이후 시점의 데이터도 힌트로 활용하기 위해서 고안된 것이 양방향 RNN입니다.__


![](https://wikidocs.net/images/page/22886/rnn_image5_ver2.PNG)


양방향 RNN은 하나의 출력값을 예측하기 위해 기본적으로 __두 개의 메모리 셀__ 을 사용합니다. 첫번째 메모리 셀은 앞에서 배운 것처럼 __앞 시점의 은닉 상태(Forward States)__ 를 전달받아 현재의 은닉 상태를 계산합니다. 위의 그림에서는 주황색 메모리 셀에 해당됩니다. 두번째 메모리 셀은 앞에서 배운 것과는 다릅니다. 앞 시점의 은닉 상태가 아니라 __뒤 시점의 은닉 상태(Backward States)__ 를 전달 받아 현재의 은닉 상태를 계산합니다. 위의 그림에서는 초록색 메모리 셀에 해당됩니다. __그리고 이 두 개의 값 모두가 출력층에서 출력값을 예측하기 위해 사용됩니다.__

물론, 양방향 RNN도 다수의 은닉층을 가질 수 있습니다. 아래의 그림은 양방향 순환 신경망에서 은닉층이 1개 더 추가되어 은닉층이 2개인 깊은(deep) 양방향 순환 신경망의 모습을 보여줍니다.

![](https://wikidocs.net/images/page/22886/rnn_image6_ver3.PNG)

다른 인공 신경망 모델들도 마찬가지이지만, 은닉층을 무조건 추가한다고 해서 모델의 성능이 좋아지는 것은 아닙니다. __은닉층을 추가하면, 학습할 수 있는 양이 많아지지만 또한 반대로 훈련 데이터 또한 그만큼 많이 필요합니다.__

양방향 순환 신경망을 파이토치로 구현할 때는 nn.RNN()의 인자인 bidirectional에 값을 True로 전달하면 됩니다. 이번에는 층이 2개인 깊은 순환 신경망이면서 양방향인 경우, 앞서 실습했던 임의의 입력에 대해서 출력이 어떻게 달라지는지 확인해봅시다.

In [54]:
# (batch_size, time_steps, input_size)
inputs = torch.Tensor(1, 10, 5)

In [55]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers = 2, batch_first=True, bidirectional = True)


In [56]:
outputs, _status = cell(inputs)


In [57]:
print(outputs.shape) # (배치 크기, 시퀀스 길이, 은닉 상태의 크기 x 2)

torch.Size([1, 10, 16])


첫번째 리턴값의 크기는 단뱡 RNN 셀 때보다 은닉 상태의 크기의 값이 두 배가 되었습니다. 여기서는 (배치 크기, 시퀀스 길이, 은닉 상태의 크기 x 2)의 크기를 가집니다. 이는 양방향의 은닉 상태 값들이 연결(concatenate)되었기 때문입니다.



In [58]:
print(_status.shape) # (층의 개수 x 2, 배치 크기, 은닉 상태의 크기)

torch.Size([4, 1, 8])


두번째 리턴값의 크기는 (층의 개수 x 2, 배치 크기, 은닉 상태의 크기)를 가집니다. 이는 정방향 기준으로는 마지막 시점에 해당되면서, 역방향 기준에서는 첫번째 시점에 해당되는 시점의 출력값을 층의 개수만큼 쌓아 올린 결과값입니다.



In [59]:
outputs

tensor([[[ 0.3498,  0.4029, -0.1311, -0.2786, -0.1753, -0.5241,  0.3668,
          -0.1880, -0.0261, -0.1114, -0.1547, -0.2100, -0.3313, -0.6132,
          -0.1574,  0.1739],
         [ 0.5186,  0.1050,  0.0982, -0.3627, -0.3918, -0.4447,  0.2556,
           0.0163,  0.0536, -0.0632, -0.0104, -0.5193, -0.1568, -0.5109,
          -0.2187,  0.2013],
         [ 0.6744,  0.1341, -0.0013, -0.3286, -0.1974, -0.4429,  0.4039,
          -0.1131,  0.0879,  0.1563, -0.0431, -0.2031, -0.2003, -0.6403,
           0.0072, -0.0701],
         [ 0.5456,  0.1566, -0.0898, -0.7758, -0.1973, -0.4581,  0.1098,
           0.0075, -0.0965,  0.6300,  0.2701, -0.5060, -0.2589,  0.0239,
          -0.3681, -0.0920],
         [-0.2908,  0.6951, -0.1778, -0.5616,  0.6698, -0.9080,  0.5026,
           0.6250, -0.9164, -0.5311, -0.9005,  0.5266, -0.5271, -0.7314,
          -0.4702,  0.0033],
         [ 0.4018,  0.0550,  0.1743, -0.1568, -0.4137, -0.5832,  0.6293,
           0.1584, -0.2834,  0.0931,  0.2192, -0.540

In [60]:
_status

tensor([[[-0.1657,  0.6262, -0.2476, -0.1113,  0.1250,  0.3851, -0.1117,
          -0.2474]],

        [[ 0.0817,  0.4460,  0.1458, -0.5316,  0.4833, -0.4617,  0.3836,
           0.4988]],

        [[ 0.5611,  0.0527,  0.1958, -0.4182,  0.0927, -0.3545,  0.3911,
          -0.0043]],

        [[-0.0261, -0.1114, -0.1547, -0.2100, -0.3313, -0.6132, -0.1574,
           0.1739]]], grad_fn=<StackBackward>)

In [63]:
len(list(cell.parameters())) # 파라미터 수

16